[package]
name = "rocket-demo-app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rocket = "0.4.7"
wasm-bindgen = "0.2"
getrandom = { version = "0.2", features = ["js"] }